<div id="df-3427acd0-cec2-4e2e-a670-f01483459f80" class="colab-df-container">
    <div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>TreeCount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Loblolly pine</td>
      <td>235</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Southern red oak</td>
      <td>65</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Sweetgum</td>
      <td>61</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Willow oak</td>
      <td>53</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Live oak</td>
      <td>50</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Water oak</td>
      <td>46</td>
    </tr>
    <tr>
      <th>6</th>
      <td>White oak</td>
      <td>41</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Scarlet oak</td>
      <td>33</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Swamp chestnut oak</td>
      <td>33</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Green ash</td>
      <td>31</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Mockernut hickory</td>
      <td>28</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Yellow-poplar</td>
      <td>28</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Northern red oak</td>
      <td>25</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Pignut hickory</td>
      <td>25</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Shortleaf pine</td>
      <td>25</td>
    </tr>
    <tr>
      <th>15</th>
      <td>American beech</td>
      <td>25</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Bitternut hickory</td>
      <td>24</td>
    </tr>
    <tr>
      <th>17</th>
      <td>American sycamore</td>
      <td>24</td>
    </tr>
    <tr>
      <th>18</th>
      <td>Eastern white pine</td>
      <td>23</td>
    </tr>
    <tr>
      <th>19</th>
      <td>Sourwood</td>
      <td>22</td>
    </tr>
    <tr>
      <th>20</th>
      <td>Bald cypress</td>
      <td>22</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Virginia pine</td>
      <td>22</td>
    </tr>
    <tr>
      <th>22</th>
      <td>Pin oak</td>
      <td>22</td>
    </tr>
    <tr>
      <th>23</th>
      <td>Pecan</td>
      <td>22</td>
    </tr>
    <tr>
      <th>24</th>
      <td>River birch</td>
      <td>21</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Red maple</td>
      <td>19</td>
    </tr>
    <tr>
      <th>26</th>
      <td>White ash</td>
      <td>18</td>
    </tr>
    <tr>
      <th>27</th>
      <td>Post oak</td>
      <td>18</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Sawtooth oak</td>
      <td>18</td>
    </tr>
    <tr>
      <th>29</th>
      <td>Winged elm</td>
      <td>16</td>
    </tr>
    <tr>
      <th>30</th>
      <td>Black cherry</td>
      <td>15</td>
    </tr>
    <tr>
      <th>31</th>
      <td>Overcup oak</td>
      <td>14</td>
    </tr>
    <tr>
      <th>32</th>
      <td>Southern magnolia</td>
      <td>14</td>
    </tr>
    <tr>
      <th>33</th>
      <td>Eastern cottonwood</td>
      <td>13</td>
    </tr>
    <tr>
      <th>34</th>
      <td>Longleaf pine</td>
      <td>13</td>
    </tr>
    <tr>
      <th>35</th>
      <td>Slash pine</td>
      <td>13</td>
    </tr>
    <tr>
      <th>36</th>
      <td>Eastern redcedar</td>
      <td>13</td>
    </tr>
    <tr>
      <th>37</th>
      <td>American basswood</td>
      <td>12</td>
    </tr>
    <tr>
      <th>38</th>
      <td>American elm</td>
      <td>9</td>
    </tr>
    <tr>
      <th>39</th>
      <td>Black walnut</td>
      <td>9</td>
    </tr>
    <tr>
      <th>40</th>
      <td>Eastern hophornbeam</td>
      <td>7</td>
    </tr>
    <tr>
      <th>41</th>
      <td>Shagbark hickory</td>
      <td>6</td>
    </tr>
    <tr>
      <th>42</th>
      <td>Blackgum</td>
      <td>5</td>
    </tr>
    <tr>
      <th>43</th>
      <td>Black oak</td>
      <td>5</td>
    </tr>
    <tr>
      <th>44</th>
      <td>American hornbeam, musclewood</td>
      <td>5</td>
    </tr>
    <tr>
      <th>45</th>
      <td>Sugar maple</td>
      <td>5</td>
    </tr>
    <tr>
      <th>46</th>
      <td>Common persimmon</td>
      <td>4</td>
    </tr>
    <tr>
      <th>47</th>
      <td>Boxelder</td>
      <td>4</td>
    </tr>
    <tr>
      <th>48</th>
      <td>Slippery elm</td>
      <td>4</td>
    </tr>
    <tr>
      <th>49</th>
      <td>Chestnut oak</td>
      <td>4</td>
    </tr>
    <tr>
      <th>50</th>
      <td>Florida maple</td>
      <td>3</td>
    </tr>
    <tr>
      <th>51</th>
      <td>Silver maple</td>
      <td>2</td>
    </tr>
    <tr>
      <th>52</th>
      <td>Sugarberry</td>
      <td>2</td>
    </tr>
    <tr>
      <th>53</th>
      <td>Honeylocust</td>
      <td>1</td>
    </tr>
    <tr>
      <th>54</th>
      <td>Flowering dogwood</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>
    <div class="colab-df-buttons">
      
  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-3427acd0-cec2-4e2e-a670-f01483459f80')"
            title="Convert this dataframe to an interactive table."
            style="display:none;">
      
  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"/>
  </svg>
    </button>
    
  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-3427acd0-cec2-4e2e-a670-f01483459f80 button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-3427acd0-cec2-4e2e-a670-f01483459f80');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>
  
    </div>
  </div>

Original species: 55
Kept species: 25
<div id="df-b2af8d8c-3ff5-44e1-bdf5-6c7db94daf90" class="colab-df-container">
    <div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Species</th>
      <th>TreeCount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Loblolly pine</td>
      <td>235</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Southern red oak</td>
      <td>65</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Sweetgum</td>
      <td>61</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Willow oak</td>
      <td>53</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Live oak</td>
      <td>50</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Water oak</td>
      <td>46</td>
    </tr>
    <tr>
      <th>6</th>
      <td>White oak</td>
      <td>41</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Swamp chestnut oak</td>
      <td>33</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Scarlet oak</td>
      <td>33</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Green ash</td>
      <td>31</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Mockernut hickory</td>
      <td>28</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Yellow-poplar</td>
      <td>28</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Shortleaf pine</td>
      <td>25</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Northern red oak</td>
      <td>25</td>
    </tr>
    <tr>
      <th>14</th>
      <td>American beech</td>
      <td>25</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Pignut hickory</td>
      <td>25</td>
    </tr>
    <tr>
      <th>16</th>
      <td>American sycamore</td>
      <td>24</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Bitternut hickory</td>
      <td>24</td>
    </tr>
    <tr>
      <th>18</th>
      <td>Eastern white pine</td>
      <td>23</td>
    </tr>
    <tr>
      <th>19</th>
      <td>Virginia pine</td>
      <td>22</td>
    </tr>
    <tr>
      <th>20</th>
      <td>Pin oak</td>
      <td>22</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Pecan</td>
      <td>22</td>
    </tr>
    <tr>
      <th>22</th>
      <td>Sourwood</td>
      <td>22</td>
    </tr>
    <tr>
      <th>23</th>
      <td>Bald cypress</td>
      <td>22</td>
    </tr>
    <tr>
      <th>24</th>
      <td>River birch</td>
      <td>21</td>
    </tr>
  </tbody>
</table>
</div>
    <div class="colab-df-buttons">
      
  <div class="colab-df-container">
    <button class="colab-df-convert" onclick="convertToInteractive('df-b2af8d8c-3ff5-44e1-bdf5-6c7db94daf90')"
            title="Convert this dataframe to an interactive table."
            style="display:none;">
      
  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960">
    <path d="M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z"/>
  </svg>
    </button>
    
  <style>
    .colab-df-container {
      display:flex;
      gap: 12px;
    }

    .colab-df-convert {
      background-color: #E8F0FE;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      display: none;
      fill: #1967D2;
      height: 32px;
      padding: 0 0 0 0;
      width: 32px;
    }

    .colab-df-convert:hover {
      background-color: #E2EBFA;
      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);
      fill: #174EA6;
    }

    .colab-df-buttons div {
      margin-bottom: 4px;
    }

    [theme=dark] .colab-df-convert {
      background-color: #3B4455;
      fill: #D2E3FC;
    }

    [theme=dark] .colab-df-convert:hover {
      background-color: #434B5C;
      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);
      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));
      fill: #FFFFFF;
    }
  </style>

    <script>
      const buttonEl =
        document.querySelector('#df-b2af8d8c-3ff5-44e1-bdf5-6c7db94daf90 button.colab-df-convert');
      buttonEl.style.display =
        google.colab.kernel.accessAllowed ? 'block' : 'none';

      async function convertToInteractive(key) {
        const element = document.querySelector('#df-b2af8d8c-3ff5-44e1-bdf5-6c7db94daf90');
        const dataTable =
          await google.colab.kernel.invokeFunction('convertToInteractive',
                                                    [key], {});
        if (!dataTable) return;

        const docLinkHtml = 'Like what you see? Visit the ' +
          '<a target="_blank" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'
          + ' to learn more about interactive tables.';
        element.innerHTML = '';
        dataTable['output_type'] = 'display_data';
        await google.colab.output.renderOutput(dataTable, element);
        const docLink = document.createElement('div');
        docLink.innerHTML = docLinkHtml;
        element.appendChild(docLink);
      }
    </script>
  </div>
  
    </div>
  </div>

Removed Species:
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>count</th>
    </tr>
    <tr>
      <th>Species</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Red maple</th>
      <td>19</td>
    </tr>
    <tr>
      <th>White ash</th>
      <td>18</td>
    </tr>
    <tr>
      <th>Post oak</th>
      <td>18</td>
    </tr>
    <tr>
      <th>Sawtooth oak</th>
      <td>18</td>
    </tr>
    <tr>
      <th>Winged elm</th>
      <td>16</td>
    </tr>
    <tr>
      <th>Black cherry</th>
      <td>15</td>
    </tr>
    <tr>
      <th>Overcup oak</th>
      <td>14</td>
    </tr>
    <tr>
      <th>Southern magnolia</th>
      <td>14</td>
    </tr>
    <tr>
      <th>Eastern cottonwood</th>
      <td>13</td>
    </tr>
    <tr>
      <th>Longleaf pine</th>
      <td>13</td>
    </tr>
    <tr>
      <th>Slash pine</th>
      <td>13</td>
    </tr>
    <tr>
      <th>Eastern redcedar</th>
      <td>13</td>
    </tr>
    <tr>
      <th>American basswood</th>
      <td>12</td>
    </tr>
    <tr>
      <th>American elm</th>
      <td>9</td>
    </tr>
    <tr>
      <th>Black walnut</th>
      <td>9</td>
    </tr>
    <tr>
      <th>Eastern hophornbeam</th>
      <td>7</td>
    </tr>
    <tr>
      <th>Shagbark hickory</th>
      <td>6</td>
    </tr>
    <tr>
      <th>Blackgum</th>
      <td>5</td>
    </tr>
    <tr>
      <th>Black oak</th>
      <td>5</td>
    </tr>
    <tr>
      <th>American hornbeam, musclewood</th>
      <td>5</td>
    </tr>
    <tr>
      <th>Sugar maple</th>
      <td>5</td>
    </tr>
    <tr>
      <th>Common persimmon</th>
      <td>4</td>
    </tr>
    <tr>
      <th>Boxelder</th>
      <td>4</td>
    </tr>
    <tr>
      <th>Slippery elm</th>
      <td>4</td>
    </tr>
    <tr>
      <th>Chestnut oak</th>
      <td>4</td>
    </tr>
    <tr>
      <th>Florida maple</th>
      <td>3</td>
    </tr>
    <tr>
      <th>Silver maple</th>
      <td>2</td>
    </tr>
    <tr>
      <th>Sugarberry</th>
      <td>2</td>
    </tr>
    <tr>
      <th>Honeylocust</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Flowering dogwood</th>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div><br><label><b>dtype:</b> int64</label>